"""
Training Dataset for Tina AI Chatbot
300+ labeled sentences across 12 intent classes
This is what makes it a REAL ML project
"""

TRAINING_DATA = [

    # ══════════════════════════════════════
    # INTENT: greeting
    # ══════════════════════════════════════
    ("hi", "greeting"),
    ("hello", "greeting"),
    ("hey", "greeting"),
    ("hii", "greeting"),
    ("helo", "greeting"),
    ("good morning", "greeting"),
    ("good evening", "greeting"),
    ("good afternoon", "greeting"),
    ("hey there", "greeting"),
    ("howdy", "greeting"),
    ("what's up", "greeting"),
    ("sup", "greeting"),
    ("namaste", "greeting"),
    ("namaskar", "greeting"),
    ("hi tina", "greeting"),
    ("hello tina", "greeting"),
    ("hey bot", "greeting"),
    ("start", "greeting"),
    ("begin", "greeting"),
    ("help me", "greeting"),
    ("i need help", "greeting"),
    ("can you help", "greeting"),
    ("assist me", "greeting"),
    ("hi there", "greeting"),
    ("hello there", "greeting"),

    # ══════════════════════════════════════
    # INTENT: product_search
    # ══════════════════════════════════════
    ("show me phones", "product_search"),
    ("i want to buy a phone", "product_search"),
    ("looking for a smartphone", "product_search"),
    ("I need a mobile", "product_search"),
    ("show me laptops", "product_search"),
    ("I want to buy a laptop", "product_search"),
    ("best laptops available", "product_search"),
    ("show me headphones", "product_search"),
    ("I need earphones", "product_search"),
    ("wireless earbuds", "product_search"),
    ("show me smartwatches", "product_search"),
    ("I want a fitness tracker", "product_search"),
    ("show me tablets", "product_search"),
    ("I need a tablet", "product_search"),
    ("show me electronics", "product_search"),
    ("browse products", "product_search"),
    ("what products do you have", "product_search"),
    ("show all products", "product_search"),
    ("I want to buy something", "product_search"),
    ("show me cameras", "product_search"),
    ("I need a speaker", "product_search"),
    ("bluetooth speaker", "product_search"),
    ("show me smart home devices", "product_search"),
    ("kitchen appliances", "product_search"),
    ("home appliances", "product_search"),
    ("show me power banks", "product_search"),
    ("I need a kindle", "product_search"),
    ("show me gadgets", "product_search"),
    ("mujhe phone chahiye", "product_search"),
    ("mujhe laptop chahiye", "product_search"),
    ("phone dikhao", "product_search"),
    ("best mobile phones", "product_search"),
    ("top rated laptops", "product_search"),
    ("popular products", "product_search"),
    ("new arrivals", "product_search"),
    ("trending products", "product_search"),
    ("best selling products", "product_search"),
    ("recommend me a phone", "product_search"),
    ("suggest a good laptop", "product_search"),
    ("which phone should I buy", "product_search"),
    ("good earbuds", "product_search"),
    ("noise cancelling headphones", "product_search"),
    ("gaming laptop", "product_search"),
    ("budget phone", "product_search"),
    ("premium phone", "product_search"),
    ("flagship phone", "product_search"),
    ("show me iphone", "product_search"),
    ("samsung phones", "product_search"),
    ("oneplus phone", "product_search"),
    ("redmi phone", "product_search"),
    ("macbook", "product_search"),
    ("dell laptop", "product_search"),
    ("hp laptop", "product_search"),
    ("lenovo laptop", "product_search"),
    ("boat headphones", "product_search"),
    ("sony headphones", "product_search"),
    ("apple airpods", "product_search"),
    ("vacuum cleaner", "product_search"),
    ("air fryer", "product_search"),
    ("pressure cooker", "product_search"),
    ("smart bulb", "product_search"),
    ("smart plug", "product_search"),

    # ══════════════════════════════════════
    # INTENT: price_search
    # ══════════════════════════════════════
    ("phones under 10000", "price_search"),
    ("phones under 15000", "price_search"),
    ("phones under 20000", "price_search"),
    ("phones under 30000", "price_search"),
    ("laptops under 30000", "price_search"),
    ("laptops under 50000", "price_search"),
    ("laptops under 40000", "price_search"),
    ("headphones under 2000", "price_search"),
    ("earphones under 1000", "price_search"),
    ("products under 5000", "price_search"),
    ("show me items under 500", "price_search"),
    ("budget products under 1000", "price_search"),
    ("phones below 10000", "price_search"),
    ("laptops below 35000", "price_search"),
    ("less than 5000", "price_search"),
    ("items below 2000 rupees", "price_search"),
    ("products under 10000 rs", "price_search"),
    ("phone under 10000 rs", "price_search"),
    ("laptop under 50000 rupees", "price_search"),
    ("cheap phones", "price_search"),
    ("affordable laptops", "price_search"),
    ("budget smartphones", "price_search"),
    ("low price headphones", "price_search"),
    ("10000 mein phone", "price_search"),
    ("15000 ke andar phone", "price_search"),
    ("watches under 3000", "price_search"),
    ("tablets under 20000", "price_search"),
    ("smartwatch under 5000", "price_search"),

    # ══════════════════════════════════════
    # INTENT: track_order
    # ══════════════════════════════════════
    ("track my order", "track_order"),
    ("where is my order", "track_order"),
    ("order status", "track_order"),
    ("check my order", "track_order"),
    ("order tracking", "track_order"),
    ("when will my order arrive", "track_order"),
    ("track order ORD-1001", "track_order"),
    ("my order ORD-1002", "track_order"),
    ("status of my order", "track_order"),
    ("check order status", "track_order"),
    ("where is my package", "track_order"),
    ("my shipment status", "track_order"),
    ("has my order shipped", "track_order"),
    ("order not delivered", "track_order"),
    ("package not received", "track_order"),
    ("mera order kahan hai", "track_order"),
    ("order track karo", "track_order"),
    ("delivery status", "track_order"),
    ("order ORD-1003 status", "track_order"),
    ("ORD-1004", "track_order"),
    ("ORD-1005 track", "track_order"),
    ("show my recent order", "track_order"),
    ("late delivery", "track_order"),
    ("order delayed", "track_order"),
    ("shipment tracking", "track_order"),

    # ══════════════════════════════════════
    # INTENT: return_refund
    # ══════════════════════════════════════
    ("I want to return my order", "return_refund"),
    ("how to return a product", "return_refund"),
    ("return policy", "return_refund"),
    ("refund policy", "return_refund"),
    ("I want a refund", "return_refund"),
    ("can I return this", "return_refund"),
    ("exchange product", "return_refund"),
    ("replace my order", "return_refund"),
    ("wrong product received", "return_refund"),
    ("damaged product", "return_refund"),
    ("product not working", "return_refund"),
    ("defective product", "return_refund"),
    ("return window", "return_refund"),
    ("how many days for return", "return_refund"),
    ("30 day return", "return_refund"),
    ("money back", "return_refund"),
    ("product return karna hai", "return_refund"),
    ("refund kab milega", "return_refund"),
    ("want to exchange", "return_refund"),
    ("cancel and refund", "return_refund"),
    ("return request", "return_refund"),
    ("initiate return", "return_refund"),
    ("reverse pickup", "return_refund"),
    ("return not accepted", "return_refund"),

    # ══════════════════════════════════════
    # INTENT: payment
    # ══════════════════════════════════════
    ("payment options", "payment"),
    ("how to pay", "payment"),
    ("accepted payment methods", "payment"),
    ("can I pay with UPI", "payment"),
    ("GPay payment", "payment"),
    ("PhonePe payment", "payment"),
    ("Paytm accepted", "payment"),
    ("credit card payment", "payment"),
    ("debit card payment", "payment"),
    ("net banking", "payment"),
    ("cash on delivery", "payment"),
    ("COD available", "payment"),
    ("is COD available", "payment"),
    ("wallet payment", "payment"),
    ("payment failed", "payment"),
    ("payment not going through", "payment"),
    ("secure payment", "payment"),
    ("pay kaise kare", "payment"),
    ("online payment", "payment"),
    ("pay later option", "payment"),
    ("BHIM UPI", "payment"),
    ("RuPay card", "payment"),
    ("payment gateway", "payment"),

    # ══════════════════════════════════════
    # INTENT: shipping
    # ══════════════════════════════════════
    ("shipping charges", "shipping"),
    ("delivery charges", "shipping"),
    ("free shipping", "shipping"),
    ("when will it be delivered", "shipping"),
    ("delivery time", "shipping"),
    ("how long does delivery take", "shipping"),
    ("express delivery", "shipping"),
    ("same day delivery", "shipping"),
    ("shipping to my city", "shipping"),
    ("shipping cost", "shipping"),
    ("delivery fee", "shipping"),
    ("fast delivery", "shipping"),
    ("overnight shipping", "shipping"),
    ("shipping policy", "shipping"),
    ("delivery policy", "shipping"),
    ("free delivery on how much", "shipping"),
    ("kitne din mein aayega", "shipping"),
    ("delivery kab hogi", "shipping"),
    ("shipping time", "shipping"),
    ("estimated delivery", "shipping"),
    ("pin code delivery", "shipping"),

    # ══════════════════════════════════════
    # INTENT: offers_coupon
    # ══════════════════════════════════════
    ("any coupons available", "offers_coupon"),
    ("discount codes", "offers_coupon"),
    ("promo code", "offers_coupon"),
    ("offers today", "offers_coupon"),
    ("any deals", "offers_coupon"),
    ("sale going on", "offers_coupon"),
    ("coupon code", "offers_coupon"),
    ("get discount", "offers_coupon"),
    ("save money", "offers_coupon"),
    ("best offers", "offers_coupon"),
    ("festival offers", "offers_coupon"),
    ("discount on phones", "offers_coupon"),
    ("voucher", "offers_coupon"),
    ("cashback offer", "offers_coupon"),
    ("first order discount", "offers_coupon"),
    ("koi offer hai kya", "offers_coupon"),
    ("discount chahiye", "offers_coupon"),
    ("bank offer", "offers_coupon"),
    ("hdfc offer", "offers_coupon"),
    ("special offer", "offers_coupon"),

    # ══════════════════════════════════════
    # INTENT: emi
    # ══════════════════════════════════════
    ("EMI options", "emi"),
    ("no cost EMI", "emi"),
    ("installment plan", "emi"),
    ("monthly payment", "emi"),
    ("can I pay in installments", "emi"),
    ("3 month EMI", "emi"),
    ("6 month EMI", "emi"),
    ("12 month EMI", "emi"),
    ("finance options", "emi"),
    ("bajaj finserv", "emi"),
    ("zero cost EMI", "emi"),
    ("kistoon mein lena hai", "emi"),
    ("EMI kaise milega", "emi"),
    ("easy EMI", "emi"),
    ("equated monthly installment", "emi"),

    # ══════════════════════════════════════
    # INTENT: cancel_order
    # ══════════════════════════════════════
    ("cancel my order", "cancel_order"),
    ("I want to cancel", "cancel_order"),
    ("how to cancel order", "cancel_order"),
    ("order cancellation", "cancel_order"),
    ("cancel before delivery", "cancel_order"),
    ("stop my order", "cancel_order"),
    ("order cancel karna hai", "cancel_order"),
    ("don't want the product anymore", "cancel_order"),
    ("cancel and get refund", "cancel_order"),
    ("can I cancel", "cancel_order"),
    ("cancel order ORD-1001", "cancel_order"),
    ("I changed my mind", "cancel_order"),

    # ══════════════════════════════════════
    # INTENT: account
    # ══════════════════════════════════════
    ("login problem", "account"),
    ("forgot password", "account"),
    ("reset password", "account"),
    ("OTP not received", "account"),
    ("account issues", "account"),
    ("sign in problem", "account"),
    ("register new account", "account"),
    ("update profile", "account"),
    ("change phone number", "account"),
    ("delete account", "account"),
    ("account locked", "account"),
    ("password change", "account"),
    ("email not verified", "account"),
    ("login nahi ho raha", "account"),

    # ══════════════════════════════════════
    # INTENT: goodbye
    # ══════════════════════════════════════
    ("bye", "goodbye"),
    ("goodbye", "goodbye"),
    ("see you", "goodbye"),
    ("thanks", "goodbye"),
    ("thank you", "goodbye"),
    ("ok thanks", "goodbye"),
    ("that's all", "goodbye"),
    ("nothing else", "goodbye"),
    ("I'm done", "goodbye"),
    ("no more questions", "goodbye"),
    ("shukriya", "goodbye"),
    ("dhanyawad", "goodbye"),
    ("great thanks", "goodbye"),
    ("perfect", "goodbye"),
    ("awesome thanks", "goodbye"),
]

# Intent labels for reference
INTENTS = [
    "greeting",
    "product_search",
    "price_search",
    "track_order",
    "return_refund",
    "payment",
    "shipping",
    "offers_coupon",
    "emi",
    "cancel_order",
    "account",
    "goodbye"
]
